### ISSUE TITLE
DELETE app not working

### ISSUE THREAD

**Issue by lomadi** [bibbox/sys-bibbox-backend-liferay#16]
DELETE app does not delete all files, e.g. when in the data directory something is created, e.g. at the orientDB APP

**Comment by reihsr** [comment]
An additional script is needed to delete some containers where files are created as root in the docker container.

**Comment by reihsr** [comment]
/etc/bibbox/delete_root_folder_applications.sh
attributes: root:root 744
`#!/bin/bash
source bibbox.cfg
if [[ "$1" = "" ]]; then
  echo "ERROR: No Instanc set to delete."
elif [[ "$1" = "*" ]]; then
  echo "ERROR: * Not allowed as parameter."
elif [[ "$1" = "/" ]]; then
  echo "ERROR: / Not allowed in the parameter String."
elif [[ "$1" = "\"" ]]; then
  echo "ERROR: / Not allowed in the parameter String."
elif [[ $# != 1 ]]; then
  echo "ERROR: Number of parameters not matching."
else
  rm -r "$bibboxdir/$bibboxinstancefolder/$1"
fi`

/etc/sudoers.d/liferaydeletescript
attributes: root:root 220
`liferay ALL = NOPASSWD: /etc/bibbox/delete_root_folder_applications.sh`
