### ISSUE TITLE
Toggle Maintenance API Bug

### ISSUE THREAD

**Issue by Balfear** [bibbox/sys-bibbox-backend-liferay#2]
The API for toggling the maintenance mode of an installed application ( **BIBBOXDocker-portlet.toggl-instance-maintenance-status** ) seems to sometimes return the same state (true or false) twice or more in a row. Apparently the status is **not toggled or not updated correctly**. Tested on an instance of PhenoTips.

Sidenote: The API name misses an "e" character at the end of "toggl".

**Comment by reihsr** [comment]
Need Testing if changes to running container systems workes
