### ISSUE TITLE
datastore is not in forbidden ID's

### ISSUE THREAD

**Issue by lomadi** [bibbox/sys-bibbox-backend-liferay#21]
datastore is not in forbidden ID's
maybe we should even change datastore to  bb-iir

**Comment by Balfear** [comment]
Newest commit in sys-frontend prevents "datastore" from being used as instance id.

**Comment by Balfear** [comment]
After discussion, we realised it would be more clean to add "datastore" to the forbidden ids in backend. Needs to be updated in install-info API.
