### ISSUE TITLE
Twice as much LOG lines as defined

### ISSUE THREAD

**Issue by Balfear** [bibbox/sys-bibbox-backend-liferay#4]
The API for getting the latest X lines of an application log ( **BIBBOXDocker-portlet.get-instance-log** ) seems to have a bug where it always **returns twice as many lines as defined**. E.g. 20 lines instead of 10

**Comment by reihsr** [comment]
`docker-compose logs --tail **5**` return 5 rows of the log of every container (also not in order of occurrence so the logs can jump)

**Comment by reihsr** [comment]
Change to new structure of returning the log files.
Array of objects:
Name of container:
log:
command to get log:
