### ISSUE TITLE
Activity center should not always be accessible

### ISSUE THREAD

**Issue by Balfear** [bibbox/sys-bibbox-backend-liferay#6]
The activity center button in the page navigation should not be accessible until an user with "Admin" role or higher logs in. The button should not be rendered when no user or an user without the necessary permissions is logged in.

**Comment by lomadi** [comment]
maybe we will mot provide a user/operator role within the portal. the admin can e.g. generate a new site, if using liferay, or distribute the app links to users through other channels. 

in the demo version, everybody can/should see the activities.

**Comment by Balfear** [comment]
Sure, for the demo case it might not matter, but as it stands now, the latest 10 activities are visible even without logging in at all. In my opinion exposing the current ongoings within the system should be prevented for non authorized users. I propose to not render the activity center in the page navigation as long as no user is logged in.

**Comment by reihsr** [comment]
Removed for not logged in users
