### ISSUE TITLE
Activity title bug when installing an application

### ISSUE THREAD

**Issue by Balfear** [bibbox/sys-bibbox-backend-liferay#8]
There seems to be an issue with the activity title when installing an application via the provided API ( **BIBBOXDocker-portlet.install-application** ). **Instead of the applications store shortname it displays "null"**. E.g. "Installing null as PhenoTips Test" instead of "Installing Phenotips as PhenoTips Test".

**Comment by reihsr** [comment]
Fixed and tested, changed to applicationId
