### ISSUE TITLE
Additional dashboard states

### ISSUE THREAD

**Issue by Balfear** [bibbox/sys-bibbox-backend-liferay#9]
For the dashboard view of an specific application it might be a good idea to introduce some new states to give users a better feedback and prevent unnecessary inputs.
For this reason, I propose the addition of the following states, all of them for disabling the dashboard controls just like the "installing" state.

- stopping: while the application is trying to stop
- starting: while the application is trying to start
- restarting: while the application is trying to restart
- deleting: while the application is being deleted

I don't think it is necessary to introduce a new state for the maintenance toggling though.

**Comment by reihsr** [comment]
implemented needs testing
